name: CI & QA Pipeline Orchestrator

on:
  push:
    branches: [ "main", "master", "develop" ]
  pull_request:
    branches: [ "main", "master", "develop" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  static-analysis:
    name: Lint & Static Analysis
    uses: ./.github/workflows/static-analysis.yml

  unit-tests:
    name: Unit Testing
    uses: ./.github/workflows/unit-tests.yml

  build-release:
    name: Production Release Build
    needs: static-analysis
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/build-release.yml
    secrets: inherit

  deploy-release:
    name: Deploy Internal
    needs: build-release
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/publish-internal.yml
    secrets: inherit  

  tag-version:
    name: Create Tag Version
    needs: deploy-release
    if: github.ref == 'refs/heads/master'
    permissions:
      contents: write
    uses: ./.github/workflows/release-tagger.yml
