name: Publish Internal

on:
  workflow_call:
   
  jobs:
  
   deploy-google-play:
     name: Deploy to Google Play Console
     runs-on: ubuntu-latest
     steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout private properties repository
        uses: actions/checkout@v4
        with:
          repository: nano871022/japl-properties
          token: ${{ secrets.GH_PAT_PRIVATE_REPO }}
          path: private-props

      - name: Download build artifact Mobile
        uses: actions/download-artifact@v4
        with:
          name: release-bundle # Reemplaza con el nombre exacto con el que subiste el archivo en el paso previo
          path: app/build/outputs/bundle/release/ # Ruta donde Google Play Action espera encontrar el archivo
          
      - name: Download build artifact WearOS
        uses: actions/download-artifact@v4
        with:
          name: release-bundle-wearos # Reemplaza con el nombre exacto con el que subiste el archivo en el paso previo
          path: app/build/outputs/bundle/release/ # Ruta donde Google Play Action espera encontrar el archivo          

      - name: Upload Mobile to Google Play Console (Internal Track)
        uses: r0adkll/upload-google-play@v3
        with:
          service-account-json-PlainText: private-props/synapseefit/synapsefit-507614-2b30a67ac3fb.json
          packageName: 'co.japl.android.synapsefit' # Reemplaza con tu applicationId / package name real
          releaseFiles: app/build/outputs/bundle/release/*.aab
          track: internal
          whatsNewDirectory: distribution/whats-new

      - name: Upload WearOS to Google Play Console (Internal Track)
        uses: r0adkll/upload-google-play@v3
        with:
          service-account-json-PlainText: private-props/synapseefit/synapsefit-507614-2b30a67ac3fb.json
          packageName: 'co.japl.android.synapsefit' # Reemplaza con tu applicationId / package name real
          releaseFiles: app/build/outputs/bundle/release/*.aab
          track: internal
          whatsNewDirectory: distribution/whats-new
