name: Publish Internal

on:
  workflow_call:

jobs:

   deploy-google-play:
     name: Deploy to Google Play Console
     runs-on: ubuntu-latest
     environment: PROD

     steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout private properties repository
        uses: actions/checkout@v4
        with:
          repository: nano871022/japl-properties
          token: ${{ secrets.TOKEN_PROP_GITHUB || secrets.GH_TOKEN || github.token }}
          path: private-props

      - name: Download build artifact Mobile
        uses: actions/download-artifact@v4
        with:
          name: app-bundle
          path: ./

      - name: Download build artifact WearOS
        uses: actions/download-artifact@v4
        with:
          name: wear-bundle
          path: ./

      - name: List build outputs
        run: |
            find ./ -type f -name "*.aab" 2>/dev/null || echo "No .aab files found"
            ls -la ./ || echo "outputs directory not found"

      - name: Upload Mobile to Google Play Console (Internal Track)
        uses: r0adkll/upload-google-play@v1.1.5
        with:
          serviceAccountJson: ${{ github.workspace }}/private-props/synapseefit/synapsefit-507614-2b30a67ac3fb.json
          packageName: 'co.japl.android.synapsefit'
          releaseFiles: ./app-bundle.aab
          track: internal
          whatsNewDirectory: distribution/whats-new

      - name: Upload WearOS to Google Play Console (Internal Track)
        uses: r0adkll/upload-google-play@v1.1.5
        with:
          serviceAccountJson: ${{ github.workspace }}/private-props/synapseefit/synapsefit-507614-2b30a67ac3fb.json
          packageName: 'co.japl.android.synapsefit'
          releaseFiles: ./wear-bundle.aab
          track: internal
          whatsNewDirectory: distribution/whats-new
