name: Static Analysis

on:
  workflow_call:

jobs:
  static-analysis:
    name: Code Formatting & Static Analysis Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Checkout japl about module
        uses: actions/checkout@v4
        with:
          repository: nano871022/japl-android-about-module
          path: about

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle Cache
        uses: gradle/actions/setup-gradle@v4

      - name: Run Ktlint & Detekt
        run: ./gradlew ktlintCheck detekt -x :about:ktlintCheck :about:detekt

      - name: Upload Static Analysis Reports Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: static-analysis-reports
          path: |
            **/build/reports/ktlint/
            **/build/reports/detekt/
          if-no-files-found: warn
